### PR TITLE
[hotfix] job launcher UserInterface dependency issues

### PR DESCRIPTION
**Pull request by jmleroux**

### CODE REVIEW

**Comment by solivier** [comment]
GTM

**Comment by phaseinducer** [comment]
GTM

**Comment by willy-ahva** [comment]
ok for the fix what for https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/ConnectorBundle/JobLauncher/SimpleJobLauncher.php ?

**Comment by jjanvier** [comment]
GTM

**Comment by jmleroux** [comment]
@willy-ahva the (temporary) fix will be different : use Oro\User instead of UserInterface. Ugly, but necessary. :|

**Pull request merged**
